spring.application.name=shree

spring.datasource.url=jdbc:h2:mem:shree
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=shree
spring.datasource.password=shree123

spring.security.user.name=shree
spring.security.user.password=shree123

management.endpoints.web.exposure.include=*


#logging
logging.file.name=logs/application.log

#jwt
#jwt.secret.key = i-am-shreeshail-and-am-implementing-jwt-tokens-and-this-is-my-secret-key1234567"